version: "3.9"

services:
  app:
    build:
        context: ..
        dockerfile: docker/Dockerfile
    container_name: rtce_app
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
    networks:
      - rtce_net

  db:
    image: postgres:14
    container_name: rtce_db
    environment:
      POSTGRES_USER: rtce
      POSTGRES_PASSWORD: rtcepass
      POSTGRES_DB: rtce_dev
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - rtce_net

  redis:
    image: redis:8.2-alpine
    container_name: rtce_redis
    ports:
      - "6379:6379"
    networks:
      - rtce_net


volumes:

networks:
  rtce_net:
    driver: bridge
